# Start with CUDA Tensorflow base image
FROM tensorflow/tensorflow:latest-gpu

# Install dependencies
RUN apt-get update && apt-get install -y \
  git \
  libhdf5-dev \
  python-h5py \
  python-yaml
# Clone Keras repo and move into it
RUN cd /root && git clone https://github.com/fchollet/keras.git && cd keras && \
  # Install
python setup.py install
